# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 996e0f0d5611b939853826e9435502d65e49bf76d774be11a2fa9624371d1aabc742507de1935ffb9b51c6bb0d662f4c47a92afbfb3c38efc5f90dad39f498cb

test:
  secret_key_base: 6f968946a0fdc19f416df7563decf1b5dd15b60c8a92f65c369c03b377cd7466925663ece6117f7ef4eee3291984239ae625eec64d2865da03aa32ddcb899042

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
